all: rot check check1 trian scrib ex1 ex2 ex5 

check: check.cc
	g++ check.cc -o check -lGL -lGLU -lglut

check1: check1.cc
	g++ check1.cc -o check1 -lGL -lGLU -lglut


rot: rot.cc
	g++ rot.cc -o rot -lGL -lGLU -lglut

scrib: scrib.cc
	g++ scrib.cc -o scrib -lGL -lGLU -lglut

trian: trian.cc
	g++ trian.cc -o trian -lGL -lGLU -lglut

ex1: ex1.cc
	g++ ex1.cc -o ex1 -lGL -lGLU -lglut
ex2: ex2.cc
	g++ ex2.cc -o ex2 -lGL -lGLU -lglut
ex3: ex3.cc
	g++ ex3.cc -o ex3 -lGL -lGLU -lglut
ex4: ex4.cc
	g++ ex4.cc -o ex4 -lGL -lGLU -lglut
ex5: ex5.cc
	g++ ex5.cc -o ex5 -lGL -lGLU -lglut
ex6: ex6.cc
	g++ ex6.cc -o ex6 -lGL -lGLU -lglut
