/* דרך קיצור - trail browser over the community My Maps layer.
 *
 * Data comes from data/trails.json, regenerated by ../build_data.py.
 * No API key is used anywhere: base tiles are open, and Street View is reached
 * by handing Google a URL rather than embedding a paid panorama widget.
 */
'use strict';

/* Swapping the base map is a one-line change here. When a Google Maps key
 * arrives, this is the seam it plugs into. */
const BASEMAPS = [
  {
    name: 'רחובות',
    url: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
    opts: { maxZoom: 19, attribution: '&copy; OpenStreetMap' }
  },
  {
    name: 'לוויין',
    url: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
    opts: { maxZoom: 19, attribution: 'Esri, Maxar, Earthstar Geographics' }
  }
];

const LINE = { weight: 5, opacity: 0.82 };
const LINE_ON = { weight: 8, opacity: 1 };
// Unselected trails stay clearly visible and clickable: picking one trail
// should not stop you browsing to the next one straight from the map.
const LINE_DIM = { weight: 4.5, opacity: 0.6 };

const el = (id) => document.getElementById(id);
const map = L.map('map', { zoomControl: false, attributionControl: true });
L.control.zoom({ position: 'topleft' }).addTo(map);

let DATA = null;
let baseIndex = 0;
let baseLayer = null;
let here = null;          // {lat, lng} once geolocation succeeds
let hereMarker = null;
let selectedId = null;
let sortMode = 'length';
const shapes = new Map();  // id -> leaflet layer

/* ---------- helpers ---------- */

const metres = (m) => (m >= 1000 ? (m / 1000).toFixed(2) + ' ק"מ' : m + ' מ׳');

function distance(a, b) {
  const R = 6371000, rad = Math.PI / 180;
  const dLat = (b.lat - a.lat) * rad, dLng = (b.lng - a.lng) * rad;
  const s = Math.sin(dLat / 2) ** 2 +
    Math.cos(a.lat * rad) * Math.cos(b.lat * rad) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(s));
}

/** Where an item sits, for "nearest to me" sorting: a segment counts from
 *  whichever of its two entrances is closer, since that is what you walk to. */
function anchors(item) {
  if (item.entries) return item.entries.map((e) => ({ lat: e.lat, lng: e.lng }));
  return [{ lat: item.lat, lng: item.lng }];
}

function nearestMetres(item) {
  if (!here) return Infinity;
  return Math.min(...anchors(item).map((a) => distance(here, a)));
}

/* Official Google URL schemes. Free, no key, and on a phone they open the
 * Google Maps app rather than a browser tab. */
const panoUrl = (lat, lng, heading) =>
  `https://www.google.com/maps/@?api=1&map_action=pano&viewpoint=${lat},${lng}` +
  `&heading=${heading || 0}&pitch=0&fov=80`;

const walkUrl = (lat, lng) =>
  `https://www.google.com/maps/dir/?api=1&destination=${lat},${lng}` +
  `&travelmode=walking&hl=iw`;

function icon(path) {
  return `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${path}"/></svg>`;
}

const I_PANO = 'M12 2a7 7 0 00-7 7c0 5.25 7 13 7 13s7-7.75 7-13a7 7 0 00-7-7zm0 9.5A2.5 2.5 0 1112 6.5a2.5 2.5 0 010 5z';
const I_WALK = 'M13.5 5.5a2 2 0 100-4 2 2 0 000 4zM9.8 8.9L7 23h2.1l1.8-8 2.1 2v6h2v-7.5l-2.1-2 .6-3A7 7 0 0019 13v-2a5 5 0 01-4.2-2.4l-1-1.6c-.4-.6-1-1-1.8-1-.3 0-.5 0-.8.2L6 8.3V13h2V9.6l1.8-.7z';

/* ---------- map layers ---------- */

function setBasemap(i) {
  const spec = BASEMAPS[i];
  if (baseLayer) map.removeLayer(baseLayer);
  baseLayer = L.tileLayer(spec.url, spec.opts).addTo(map);
  baseLayer.bringToBack();
  el('basemap').classList.toggle('on', i > 0);
  el('basemap').title = 'רקע: ' + spec.name;
}

function drawAll() {
  DATA.segments.forEach((seg) => {
    // Without stopping propagation the click also reaches the map, whose own
    // handler clears the selection we just made.
    const line = L.polyline(seg.path, { color: seg.color, ...LINE })
      .addTo(map)
      .on('click', (e) => { L.DomEvent.stopPropagation(e); select(seg.id, false); });
    line.bindTooltip(seg.name, { sticky: true, direction: 'top' });
    shapes.set(seg.id, line);
  });

  DATA.waypoints.forEach((wp) => {
    const marker = L.marker([wp.lat, wp.lng], {
      icon: L.divIcon({
        className: '',
        html: `<div class="pin"><i></i><b>${escapeHtml(wp.name)}</b></div>`,
        iconSize: null
      })
    }).addTo(map).on('click', (e) => { L.DomEvent.stopPropagation(e); select(wp.id, false); });
    shapes.set(wp.id, marker);
  });
}

function escapeHtml(s) {
  return String(s).replace(/[&<>"']/g, (c) =>
    ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}

/* ---------- selection ---------- */

function byId(id) {
  return DATA.segments.find((s) => s.id === id) ||
    DATA.waypoints.find((w) => w.id === id);
}

function highlight(id) {
  shapes.forEach((layer, key) => {
    if (!layer.setStyle) return;              // markers have no stroke style
    if (!id) layer.setStyle(LINE);
    else layer.setStyle(key === id ? LINE_ON : LINE_DIM);
  });
  const on = id && shapes.get(id);
  if (on && on.bringToFront) on.bringToFront();
}

/* `fit` recentres the map on the item. Picking from the list should do that,
 * because you have no idea where the trail is. Tapping a trail already drawn
 * on the map should not: you are looking straight at it, and yanking the
 * viewport around makes browsing from one trail to the next impossible. */
function select(id, fit = true) {
  selectedId = id;
  const item = byId(id);
  if (!item) return;

  highlight(id);
  if (fit) {
    if (item.path) {
      map.fitBounds(L.polyline(item.path).getBounds(), { padding: [50, 50], maxZoom: 18 });
    } else {
      map.setView([item.lat, item.lng], 18);
    }
  }
  showDetail(item);
}

function deselect() {
  selectedId = null;
  highlight(null);
  el('detail-view').hidden = true;
  el('list-view').hidden = false;
  renderList();
}

/* ---------- list ---------- */

function items() {
  const q = el('search').value.trim();
  let all = [...DATA.segments, ...DATA.waypoints];

  if (q) {
    const needle = q.toLowerCase();
    all = all.filter((it) =>
      (it.name + ' ' + (it.note || '') + ' ' + (it.connects || []).join(' '))
        .toLowerCase().includes(needle));
  }

  if (sortMode === 'length') {
    all.sort((a, b) => (b.length || 0) - (a.length || 0));
  } else if (sortMode === 'photos') {
    all = all.filter((it) => it.photos.length);
    all.sort((a, b) => b.photos.length - a.photos.length);
  } else if (sortMode === 'near') {
    all.sort((a, b) => nearestMetres(a) - nearestMetres(b));
  }
  return all;
}

function subtitle(it) {
  const bits = [];
  if (it.length) bits.push(metres(it.length));
  else bits.push('נקודת ציון');
  if (here) {
    const d = nearestMetres(it);
    if (isFinite(d)) bits.push(d < 1000 ? `${Math.round(d)} מ׳ ממך` : `${(d / 1000).toFixed(1)} ק"מ ממך`);
  }
  if (it.photos.length) bits.push(`${it.photos.length} תמונות`);
  if (it.note) bits.push(it.note);
  return bits.join(' · ');
}

function renderList() {
  const list = el('list');
  const rows = items();

  if (!rows.length) {
    list.innerHTML = '<li class="empty-msg">לא נמצא שביל תואם.</li>';
    return;
  }

  list.innerHTML = rows.map((it) => {
    const thumb = it.photos.length
      ? `<img class="thumb" src="${it.photos[0].thumb}" alt="" loading="lazy">`
      : `<div class="thumb empty">${it.path ? '🥾' : '📍'}</div>`;
    return `<li class="row${it.id === selectedId ? ' on' : ''}" data-id="${it.id}"
              style="color:${it.color || '#8d6e63'}">
      <span class="swatch"></span>
      ${thumb}
      <span class="txt">
        <span class="nm">${escapeHtml(it.name)}</span>
        <span class="sub">${escapeHtml(subtitle(it))}</span>
      </span>
    </li>`;
  }).join('');

  list.querySelectorAll('.row').forEach((row) => {
    row.addEventListener('click', () => select(row.dataset.id));
  });
}

/* ---------- detail ---------- */

function showDetail(it) {
  const chips = [];
  if (it.length) chips.push(`<span class="chip accent">${metres(it.length)}</span>`);
  else chips.push('<span class="chip accent">נקודת ציון</span>');
  if (it.detour && it.detour > 1.15) {
    chips.push(`<span class="chip">מתפתל ×${it.detour}</span>`);
  }
  if (here) {
    const d = nearestMetres(it);
    if (isFinite(d)) {
      chips.push(`<span class="chip">${d < 1000 ? Math.round(d) + ' מ׳' : (d / 1000).toFixed(1) + ' ק"מ'} ממך</span>`);
    }
  }

  const entries = it.entries || [{ lat: it.lat, lng: it.lng, heading: 0, view: null }];
  const names = it.connects && it.connects.length === entries.length ? it.connects : null;

  const acts = entries.map((e, i) => {
    const side = names ? names[i] : (entries.length > 1 ? `כניסה ${i + 1}` : 'המקום');
    // The camera stands on the nearest road (build_data.py works this out), so
    // the pano exists and looks at the entrance rather than out of it.
    const [vLat, vLng] = e.view || [e.lat, e.lng];
    const hint = e.likely === false
      ? `${e.road} מ׳ מהכביש הקרוב, ייתכן שאין כאן צילום 360`
      : 'מבט 360° מהרחוב אל הכניסה';
    return `<a class="act${e.likely === false ? ' weak' : ''}"
        href="${panoUrl(vLat, vLng, e.heading)}" target="_blank" rel="noopener">
      ${icon(I_PANO)}
      <span class="lbl">סטריט ויו · ${escapeHtml(side)}
        <span class="hint">${escapeHtml(hint)}</span></span>
    </a>`;
  }).join('');

  const walk = `<a class="act" href="${walkUrl(entries[0].lat, entries[0].lng)}" target="_blank" rel="noopener">
    ${icon(I_WALK)}
    <span class="lbl">ניווט רגלי לכאן<span class="hint">נפתח בגוגל מפות</span></span>
  </a>`;

  const gallery = it.photos.length ? `
    <h3>תמונות (${it.photos.length})</h3>
    <div class="gallery">
      ${it.photos.map((p, i) => `<img src="${p.thumb}" data-i="${i}" alt="${escapeHtml(it.name)}" loading="lazy">`).join('')}
    </div>` : '';

  el('detail').innerHTML = `
    <h2>${escapeHtml(it.name)}</h2>
    <div class="chips">${chips.join('')}</div>
    ${it.note ? `<p class="note">${escapeHtml(it.note)}</p>` : ''}
    <h3>הגעה</h3>
    <div class="acts">${acts}${walk}</div>
    ${gallery}
    <a class="src" href="${DATA.source}" target="_blank" rel="noopener">המפה המקורית ב-Google My Maps ↗</a>`;

  el('detail').querySelectorAll('.gallery img').forEach((img) => {
    img.addEventListener('click', () => openLightbox(it, +img.dataset.i));
  });

  el('detail').scrollTop = 0;
  el('list-view').hidden = true;
  el('detail-view').hidden = false;
}

/* ---------- lightbox ---------- */

let lbPhotos = [], lbIndex = 0, lbTitle = '';

function openLightbox(item, index) {
  lbPhotos = item.photos;
  lbTitle = item.name;
  lbIndex = index;
  el('lightbox').hidden = false;
  document.addEventListener('keydown', lbKeys);
  paintLightbox();
}

function closeLightbox() {
  el('lightbox').hidden = true;
  el('lb-img').src = '';
  document.removeEventListener('keydown', lbKeys);
}

function paintLightbox() {
  const img = el('lb-img');
  const photo = lbPhotos[lbIndex];
  img.classList.add('loading');
  el('lb-spin').hidden = false;
  img.src = photo.full;                       // full resolution, not the thumb
  img.alt = lbTitle;
  img.onload = () => { img.classList.remove('loading'); el('lb-spin').hidden = true; };
  img.onerror = () => { el('lb-spin').hidden = true; img.classList.remove('loading'); };

  el('lb-cap-text').textContent = lbTitle;
  el('lb-count').textContent = lbPhotos.length > 1 ? `(${lbIndex + 1}/${lbPhotos.length})` : '';
  const many = lbPhotos.length > 1;
  document.querySelector('.lb-prev').hidden = !many;
  document.querySelector('.lb-next').hidden = !many;
}

function step(delta) {
  lbIndex = (lbIndex + delta + lbPhotos.length) % lbPhotos.length;
  paintLightbox();
}

function lbKeys(e) {
  if (e.key === 'Escape') closeLightbox();
  // In RTL the visual "next" arrow points left, so the keys are mirrored.
  else if (e.key === 'ArrowLeft') step(1);
  else if (e.key === 'ArrowRight') step(-1);
}

/* ---------- geolocation ---------- */

function locate() {
  if (!navigator.geolocation) {
    alert('הדפדפן לא תומך באיתור מיקום.');
    return;
  }
  el('locate').classList.add('on');
  navigator.geolocation.getCurrentPosition((pos) => {
    here = { lat: pos.coords.latitude, lng: pos.coords.longitude };
    if (hereMarker) map.removeLayer(hereMarker);
    hereMarker = L.marker([here.lat, here.lng], {
      icon: L.divIcon({ className: '', html: '<div class="me"></div>', iconSize: [16, 16] }),
      interactive: false
    }).addTo(map);
    map.setView([here.lat, here.lng], 17);

    sortMode = 'near';
    document.querySelectorAll('.sort').forEach((b) =>
      b.classList.toggle('on', b.dataset.sort === 'near'));
    if (selectedId) showDetail(byId(selectedId)); else renderList();
  }, () => {
    el('locate').classList.remove('on');
    alert('לא הצלחתי לאתר את המיקום. צריך לאשר גישה למיקום, ובדפדפן זה עובד רק ב-https.');
  }, { enableHighAccuracy: true, timeout: 10000 });
}

/* ---------- panel drag (mobile) ---------- */

function wireGrip() {
  const grip = el('grip');
  let startY = 0, startH = 0, dragging = false;

  const begin = (y) => {
    dragging = true;
    startY = y;
    startH = el('panel').getBoundingClientRect().height;
  };
  const move = (y) => {
    if (!dragging) return;
    const h = Math.min(window.innerHeight * 0.9,
      Math.max(90, startH + (startY - y)));
    document.documentElement.style.setProperty('--panel-h', h + 'px');
  };
  const end = () => { dragging = false; map.invalidateSize(); };

  grip.addEventListener('pointerdown', (e) => { begin(e.clientY); grip.setPointerCapture(e.pointerId); });
  grip.addEventListener('pointermove', (e) => move(e.clientY));
  grip.addEventListener('pointerup', end);
  grip.addEventListener('pointercancel', end);
  grip.addEventListener('click', () => {
    const collapsed = el('panel').getBoundingClientRect().height < 140;
    document.documentElement.style.setProperty('--panel-h', collapsed ? '45vh' : '96px');
    setTimeout(() => map.invalidateSize(), 260);
  });
}

/* ---------- swipe on the lightbox ---------- */

function wireSwipe() {
  const stage = document.querySelector('.lb-stage');
  let x0 = null;
  stage.addEventListener('touchstart', (e) => { x0 = e.touches[0].clientX; }, { passive: true });
  stage.addEventListener('touchend', (e) => {
    if (x0 === null || lbPhotos.length < 2) return;
    const dx = e.changedTouches[0].clientX - x0;
    if (Math.abs(dx) > 45) step(dx < 0 ? 1 : -1);
    x0 = null;
  });
}

/* ---------- boot ---------- */

async function boot() {
  setBasemap(0);

  const res = await fetch('data/trails.json');
  DATA = await res.json();

  map.fitBounds(DATA.bounds, { padding: [20, 20] });
  drawAll();
  renderList();

  const s = DATA.stats;
  el('stats').textContent =
    `${s.segments} שבילים · ${metres(s.total_length)} · ${s.waypoints} נקודות ציון · ${s.photos} תמונות`;

  el('search').addEventListener('input', renderList);
  el('back').addEventListener('click', deselect);
  el('locate').addEventListener('click', locate);
  el('basemap').addEventListener('click', () => {
    baseIndex = (baseIndex + 1) % BASEMAPS.length;
    setBasemap(baseIndex);
  });

  document.querySelectorAll('.sort').forEach((btn) => {
    btn.addEventListener('click', () => {
      if (btn.dataset.sort === 'near' && !here) { locate(); return; }
      sortMode = btn.dataset.sort;
      document.querySelectorAll('.sort').forEach((b) => b.classList.toggle('on', b === btn));
      renderList();
    });
  });

  document.querySelector('.lb-close').addEventListener('click', closeLightbox);
  document.querySelector('.lb-prev').addEventListener('click', () => step(-1));
  document.querySelector('.lb-next').addEventListener('click', () => step(1));
  el('lightbox').addEventListener('click', (e) => {
    if (e.target.id === 'lightbox' || e.target.classList.contains('lb-stage')) closeLightbox();
  });

  map.on('click', () => { if (selectedId) deselect(); });

  wireGrip();
  wireSwipe();
}

boot().catch((err) => {
  el('stats').textContent = 'שגיאה בטעינת הנתונים.';
  console.error(err);
});
